/* Autogenerated with kurento-module-creator */

#include "OpencvPluginSampleImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace opencvpluginsample
{

void dummyOpencvpluginsample ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<OpencvPluginSample> object;

    s.SerializeNVP (object);
  }
}

} /* opencvpluginsample */
} /* module */
} /* kurento */
