/* Autogenerated with kurento-module-creator */

#include "OpencvPluginSample.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace opencvpluginsample
{

static std::vector<std::string> hierarchyOpencvPluginSample;
std::once_flag initFlagOpencvPluginSample;

static void
initHierarchy ()
{
  hierarchyOpencvPluginSample.push_back("kurento.OpenCVFilter");
  hierarchyOpencvPluginSample.push_back("kurento.Filter");
  hierarchyOpencvPluginSample.push_back("kurento.MediaElement");
  hierarchyOpencvPluginSample.push_back("kurento.MediaObject");
}

const std::vector<std::string> &
OpencvPluginSample::getHierarchy () const
{
  std::call_once (initFlagOpencvPluginSample,initHierarchy);
  return hierarchyOpencvPluginSample;
}

const std::string&
OpencvPluginSample::getType () const {
  static std::string typeName = "OpencvPluginSample";

  return typeName;
}

const std::string&
OpencvPluginSample::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
OpencvPluginSample::getModule () const {
  static std::string moduleName =  "opencvpluginsample";

  return moduleName;
}

} /* opencvpluginsample */
} /* module */
} /* kurento */
